
spring:
  datasource:
    username: root
    password: dnwjd123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://my-mysql:3306/todo"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
